### ISSUE TITLE
Channel is unrecoverably broken and will be disposed

### ISSUE THREAD

**Issue by humodev** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#6]
Hello,
I'm getting the following errors when I try to run the FPVDemo.

```
03-04 17:45:16.946  26645-26645/com.sandiego.dmaidana.dji_camera_demo E/com.sandiego.dmaidana.dji_camera_demo.CameraActivity﹕ onResume

03-04 17:45:17.056  26645-26645/com.sandiego.dmaidana.dji_camera_demo E/com.sandiego.dmaidana.dji_camera_demo.CameraActivity﹕ onSurfaceTextureAvailable

03-04 17:45:17.056  26645-26645/com.sandiego.dmaidana.dji_camera_demo E/com.sandiego.dmaidana.dji_camera_demo.CameraActivity﹕ mCodecManager is null 2

03-04 17:45:17.066  26645-26672/com.sandiego.dmaidana.dji_camera_demo E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-1924

    Process: com.sandiego.dmaidana.dji_camera_demo, PID: 26645
    java.lang.NullPointerException
            at a.a.b.d.f.a(Unknown Source)
            at dji.midware.data.manager.P3.g.run(Unknown Source)
            at java.lang.Thread.run(Thread.java:841)

03-04 17:45:17.086     994-1152/? E/InputDispatcher﹕ channel '42c6d4a0 com.sandiego.dmaidana.dji_camera_demo/com.sandiego.dmaidana.dji_camera_demo.CameraActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

Maybe you can help me here. 
Thank you

**Comment by dji-dev** [comment]
Hi, does the FPVDemo crash on your Android device when you get these errors? Also could you tell me the following infos:
1.  Which android device and Android System you are using? 
2. Which version of Android Studio you are using? 
3. Which DJI Drone you are using to run the FPVDemo?
Thanks!
